=== mbits-libs/git2-cxx/tools/json_tests/schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "type": "object",
    "required": ["args", "expected"],
    "properties": {
        "$schema": {"type": "string"},
        "linear": {"type": "boolean"},
        "disabled": {"type": ["string", "boolean"]},
        "lang": {"type": "boolean"},
        "args": {"type": "string"},
        "post": {"type": ["string", "array"], "items": {"type": "string"}},
        "expected": {"type": ["array", "null"]},
        "patches": {
            "type": "object",
            "properties": {
                "^$": {"not": {}},
                "^.+$": {"type": "string"}
            }
        },
        "prepare": {
            "type": ["string", "array"],
            "items": {"type": ["string", "array"], "items": {"type": "string"}}
        },
        "cleanup": {
            "type": ["string", "array"],
            "items": {"type": ["string", "array"], "items": {"type": "string"}}
        }
    },
    "additionalProperties": false,
    "default": {}
}

=== mbits-libs/git2-cxx/apps/tests/main-set/016-collect/12-collect-msvc.json
{
    "$schema": "../../../../tools/json_tests/schema.json",
    "args": "collect",
    "patches": {
        "\\[([^]]+)\\] [0-9.]+ s": "[\\1] #.## s"
    },
    "expected": [
        0,
        "",
        [
            "[toolkit] MSVC 17.01.74656 (from $TMP/dir/.covcollect)",
            "  [occ] $TMP/mocks/OpenCppCoverage",
            "  [outfile] <bin>/OpenCppCoverage/cobertura.xml",
            "[report] start...",
            "[report] #.## s",
            "[files] 1",
            "[lines] 2 / 2",
            "[functions] 0 / 0",
            "[i/o] $TMP/dir/build/cov-collect.json\n"
        ]
    ],
    "prepare": [
        "mkdirs '$TMP/dir'",
        "cd '$TMP/dir'",
        "git init",
        "cov init",
        "git commit -m 'initial' --allow-empty",
        "mkdirs build/OpenCppCoverage",
        "cp '$DATA/covcollect/OpenCppCoverage.xml' build/OpenCppCoverage/cobertura.xml",
        "touch src/main.cc",
        "mock cl.exe cl.exe",
        "mock OpenCppCoverage OpenCppCoverage",
        "generate '$DATA/covcollect/ini' .covcollect 'COMPILER=$TMP/mocks/cl.exe'",
        "generate '$DATA/covcollect/OpenCppCoverage.xml' build/OpenCppCoverage/cobertura.xml 'SOURCES=$TMP/dir'"
    ]
}

=== mbits-libs/git2-cxx/apps/tests/main-set/012-checkout/139-checkout-start-point.json
{
    "args": "checkout -b branch-name G~",
    "post": [
        "branch --show-current",
        "log --oneline -n1"
    ],
    "expected": [
        0,
        [
            "branch-name",
            "",
            "dd6999226    0%  Commit H b2a86e548@main\n"
        ],
        ""
    ],
    "prepare": [
        "unpack $DATA/revparse.tar $TMP",
        "cd $TMP/revparse",
        "cov log --oneline"
    ]
}

=== mbits-libs/git2-cxx/apps/tests/main-set/016-report-C/01-strip-excludes-help-win32.json
{
    "disabled": "linux",
    "args": "report $DATA/empty-coverage.json -f strip-excludes -o ignored -- --help",
    "expected": [
        0,
        [
            "usage: strip-excludes [-h] [--src <dir>] [--compiler <name>] [--os <name>] [-v]",
            "",
            "optional arguments:",
            " -h, --help        shows this help message and exits",
            " --src <dir>       points to root of source files; defaults to current directory",
            " --compiler <name> adds the name of current compiler to list of markers; defaults to 'msvc'",
            " --os <name>       adds the name of current platform to list of markers; defaults to 'win32'",
            " -v                shows more output\n"
        ],
        ""
    ],
    "prepare": [
        "unpack $DATA/repo.git.tar $TMP",
        "cd '$TMP/repo.git'",
        "cov init"
    ]
}

=== mbits-libs/git2-cxx/apps/tests/main-set/015-filters-A/02-strip-excludes-osOS.json
{
    "$schema": "../../runner-schema.json",
    "args": "report -f strip-excludes '$DATA/extensions/report-strip.json' -- --os OS",
    "post": ["show HEAD:main.cc"],
    "expected": [
        0,
        [
            "\u001b[31m[main $REPORT]\u001b[m Commit \"extensions\"",
            " one file, \u001b[31m 50%\u001b[m (5/10, -5), Fn\u001b[31m 40%\u001b[m (2/5)",
            " \u001b[2;37mbased on\u001b[m \u001b[2;33m$HEAD@main\u001b[m",
            " parent $PARENT",
            " \u001b[2;37mcontains $BUILD:\u001b[m \u001b[31m 50%\u001b[m",
            "",
            "file main.cc",
            "blob 8413b254a0751500a3f50ecb1dd93ae4fbf12658",
            "functions 2efee5e14da1591abe9e2af91e246c6e38199117",
            "lines b0815db9957ba028c131708a2bb7df42d5084aaf",
            "stats 40 10 5, 5 2, 0 0",
            "",
            "+-----------+--------------+---------+--------------+---------+----------+---------+------------+",
            "| Name      |   % Funcs    | Missing |   % Lines    | Visited | Relevant | Missing | Line count |",
            "+-----------+--------------+---------+--------------+---------+----------+---------+------------+",
            "|   main.cc | 40.00 +40.00 |    3 +3 | 50.00 +50.00 |    5 +5 |   10 +10 |    5 +5 |     40 +40 |",
            "+-----------+--------------+---------+--------------+---------+----------+---------+------------+",
            "",
            "  1 |    |  module;",
            "  2 |    |  import std;",
            "  3 |    |  ",
            "      0x | partial_function_exclusion1",
            "  4 | 0x | -void partial_function_exclusion() /*after*/ {",
            "  5 | 0x | -    line1();",
            "  6 |    |  // GCOV_EXCL_START[OS]",
            "  7 |    |      line2();",
            "  8 |    |      line3();",
            "  9 |    |      line4();",
            " 10 |    |  }",
            " 11 |    |  ",
            " 12 |    |  // GCOV_EXCL_STOP",
            " 13 |    |  ",
            "      0x | sep1",
            " 14 | 4x | +void sep1() {}",
            " 15 |    |  // GCOV_EXCL_START",
            " 16 |    |  ",
            "      0x | partial_function_exclusion2",
            " 17 |    |  void partial_function_exclusion1() /*before*/ {",
            " 18 |    |      line1();",
            " 19 |    |      line2();",
            " 20 |    |  // GCOV_EXCL_STOP",
            " 21 | 0x | -    line3();",
            " 22 | 0x | -    line4();",
            " 23 | 0x | -}",
            " 24 |    |  ",
            "      1x | sep2",
            " 25 | 5x | +void sep2() {}",
            " 26 |    |  ",
            "\n"
        ],
        "strip-excludes: excluded 15 lines, 1 function\n"
    ],
    "prepare": [
        "unpack $DATA/extensions.tar $TMP",
        "cd '$TMP/extensions'"
    ]
}

=== mbits-libs/git2-cxx/apps/tests/main-set/014-show/147-show-no-args.json
{
    "$schema": "../../runner-schema.json",
    "args": "show",
    "patches": {
        "report [0-9a-f]{40}": "report $OID",
        "build  [0-9a-f]{40} (.*)": "build  $BUILD_HASH \\1"
    },
    "expected": [
        0,
        [
            "report $OID",
            "commit 3845124429f44888c0152dc1929ec6853bc1c9f0",
            "build  $BUILD_HASH [ 67%]",
            "GitBranch: main",
            "Coverage:  [ 67%] 2/3 (fail)",
            "Author:    Johnny Appleseeed <johnny@appleseed.com>",
            "Added:     $DATE",
            "",
            "      second",
            "",
            "+-------+---------+---------+----------+---------+------------+",
            "| Name  | % Lines | Visited | Relevant | Missing | Line count |",
            "+-------+---------+---------+----------+---------+------------+",
            "| D src |   66.67 |       2 |        3 |       1 |          5 |",
            "+-------+---------+---------+----------+---------+------------+\n"
        ],
        ""
    ],
    "prepare": [
        "unpack $DATA/repo.git.tar $TMP",
        "cd '$TMP'",
        "git clone repo.git",
        "cd '$TMP/repo'",
        "cov init",
        "cov report $DATA/build-coverage.json -f create-report"
    ]
}

=== mbits-libs/git2-cxx/apps/tests/main-set/008-report-B/076-report-one-file.json
{
    "args": "report $DATA/build-coverage.json -f create-report",
    "patches": {
        "\u001b\\[31m\\[main [0-9a-fA-F]+\\]\u001b\\[m second": "\u001b[31m[main $REPORT]\u001b[m second"
    },
    "expected": [
        0,
        [
            "\u001b[31m[main $REPORT]\u001b[m second",
            " one file, \u001b[31m67%\u001b[m (2/3, -1)",
            " \u001b[2mbased on \u001b[33m384512442@main\u001b[m\n"
        ],
        "[ADD] src/main.cc\n"
    ],
    "prepare": [
        "unpack $DATA/repo.git.tar $TMP",
        "cd '$TMP'",
        "git clone repo.git",
        "cd '$TMP/repo'",
        "cov init"
    ]
}

=== mbits-libs/git2-cxx/apps/tests/main-set/012-checkout/137-checkout-tag.json
{
    "args": "checkout G",
    "post": [
        "branch --show-current",
        "log --oneline -n1"
    ],
    "expected": [
        0,
        "8b9c7b3b7    0%  Commit G e9ef8f01e@main\n",
        ""
    ],
    "prepare": [
        "unpack $DATA/revparse.tar $TMP",
        "cd $TMP/revparse"
    ]
}

=== mbits-libs/git2-cxx/apps/tests/main-set/016-collect/11-collect-no-output.json
{
    "$schema": "../../../../tools/json_tests/schema.json",
    "args": "collect",
    "patches": {
        "\\[([^]]+)\\] [0-9.]+ s": "[\\1] #.## s",
        "(.+)\\.exe": "\\1"
    },
    "expected": [
        1,
        "",
        [
            "[toolkit] GNU 17.0.1 (from $TMP/dir/.covcollect)",
            "  [gcov] $TMP/mocks/gcov",
            "[report] start...",
            "[0/0] finished        ",
            "[report] #.## s",
            "[files] 0",
            "[lines] 0 / 0",
            "[functions] 0 / 0",
            "[i/o] cannot open $TMP/dir/build/cov-collect.json\n"
        ]
    ],
    "prepare": [
        "mkdirs '$TMP/dir'",
        "cd '$TMP/dir'",
        "git init",
        "cov init",
        "git commit -m 'initial' --allow-empty",
        "mkdirs build/cov-collect.json",
        "mock hal9000-lcars-GLaDOS-g++-17 g++",
        "mock hal9000-lcars-GLaDOS-gcov-17 gcov",
        "generate '$DATA/covcollect/ini' .covcollect 'COMPILER=$TMP/mocks/g++'"
    ]
}
