=== mbits-libs/git2-cxx/tools/json_tests/schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "type": "object",
    "required": ["args", "expected"],
    "properties": {
        "$schema": {"type": "string"},
        "linear": {"type": "boolean"},
        "disabled": {"type": ["string", "boolean"]},
        "lang": {"type": "boolean"},
        "args": {"type": "string"},
        "post": {"type": ["string", "array"], "items": {"type": "string"}},
        "expected": {"type": ["array", "null"]},
        "patches": {
            "type": "object",
            "properties": {
                "^$": {"not": {}},
                "^.+$": {"type": "string"}
            }
        },
        "prepare": {
            "type": ["string", "array"],
            "items": {"type": ["string", "array"], "items": {"type": "string"}}
        },
        "cleanup": {
            "type": ["string", "array"],
            "items": {"type": ["string", "array"], "items": {"type": "string"}}
        }
    },
    "additionalProperties": false,
    "default": {}
}

=== mbits-libs/git2-cxx/apps/tests/main-set/009-report-B/080-report-on-detached.json
{
    "$schema": "../../../../build/downloads/runner-schema.json",
    "args": "report $DATA/build-coverage-2-files.json -f create-report",
    "patches": {"\u001b\\[0;49;90m\\[master [0-9a-fA-F]+\\] (.+)": "\u001b[0;49;90m[master $COMMIT] \\1"},
    "expected": [
        0,
        [
            "\u001b[31m[detached HEAD $REPORT]\u001b[m reported files",
            " 2 files, \u001b[33m 86%\u001b[m (6/7, -1)",
            " \u001b[2;37mbased on\u001b[m \u001b[2;33m$HEAD@main\u001b[m",
            " parent $PARENT",
            " \u001b[2;37mcontains $BUILD:\u001b[m \u001b[33m 86%\u001b[m\n"
        ],
        [
            "[ADD] src/main.cc",
            "[ADD] src/greetings.cc",
            "git config core.fsmonitor false",
            "git add src/main.cc src/greetings.cc",
            "git commit -m 'reported files'",
            "\u001b[0;49;90m[master $COMMIT] reported files\u001b[m",
            "\u001b[0;49;90m 2 files changed, 13 insertions(+)\u001b[m",
            "\u001b[0;49;90m create mode 100644 src/greetings.cc\u001b[m",
            "\u001b[0;49;90m create mode 100644 src/main.cc\u001b[m",
            "cov report: warning: src/greetings.cc was modified after the report\n"
        ]
    ],
    "prepare": [
        "unpack $DATA/repo.git.tar $TMP",
        "cd '$TMP'",
        "git clone repo.git",
        "cd '$TMP/repo'",
        "cov init",
        "cov report $DATA/build-coverage.json -f create-report",
        "detach $TMP/repo/.git/.covdata"
    ]
}

=== mbits-libs/git2-cxx/apps/tests/main-set/016-report-C/04-strip-excludes-verbose-3-linux.json
{
    "disabled": "win32",
    "args": "report $DATA/strip-excludes/coverage-1.json -f strip-excludes -o- -- -vv --os l-cars --compiler gcc",
    "expected": [
        0,
        "{\"$schema\":\"https://raw.githubusercontent.com/mzdun/cov/v0.20.0/apps/report-schema.json\",\"git\":{\"branch\":\"main\",\"head\":\"f8632047e4ea88f5e30bf57570694e5b145c5c0d\"},\"files\":[{\"name\":\"file.cc\",\"digest\":\"sha1:c2d41d07c18b314be45063cd145ca2f9019fb893\",\"line_coverage\":{\"3\":0}}]}",
        [
            "verbose: ON",
            "markers: l-cars and gcc.",
            "sources: $TMP/repo",
            "\u001b[1;37m$TMP/repo/file.cc:12:5:\u001b[m \u001b[1;35mwarning:\u001b[m found GCOV_EXCL_END; did you mean GCOV_EXCL_STOP?",
            "\u001b[1;37m$TMP/repo/file.cc:17:5:\u001b[m \u001b[1;35mwarning:\u001b[m double start: found GCOV_EXCL_START",
            "\u001b[1;37m$TMP/repo/file.cc:8:5:\u001b[m \u001b[1;36mnote:\u001b[m see previous start",
            "-- file.cc:4",
            "     0 | \u001b[2;49;30m}  // GCOV_EXCL_LINE\u001b[m",
            "-- file.cc:17",
            "       | \u001b[2;49;30m\t// GCOV_EXCL_START\u001b[m",
            "       | \u001b[2;49;30m\tfoo();\u001b[m",
            "       | \u001b[2;49;30m\t// GCOV_EXCL_STOP\u001b[m",
            "strip-excludes: excluded one line.\n"
        ]
    ],
    "prepare": [
        "unpack $DATA/repo.git.tar $TMP",
        "cd '$TMP'",
        "git clone repo.git",
        "cd repo",
        "cov init",
        "cp '$DATA/strip-excludes/file-1.cc' 'file.cc'"
    ]
}

=== mbits-libs/git2-cxx/apps/tests/main-set/016-collect/09-collect-gcc-triple.json
{
    "$schema": "../../runner-schema.json",
    "args": "collect",
    "disabled": true,
    "patches": {
        "\\[([^]]+)\\] [0-9.]+ s": "[\\1] #.## s"
    },
    "expected": null,
    "prepare": [
        "mkdirs '$TMP/collect'",
        "cd '$TMP/collect'",
        "git init",
        "cov init",
        "git commit -m 'initial' --allow-empty",
        "mock hal9000-lcars-GLaDOS-g++-17 hal9000-lcars-GLaDOS-g++-17",
        "mock hal9000-lcars-GLaDOS-gcov-17 hal9000-lcars-GLaDOS-gcov",
        "generate '$DATA/covcollect/ini' .covcollect 'COMPILER=$TMP/mocks/hal9000-lcars-GLaDOS-g++-17'"
    ]
}

=== mbits-libs/git2-cxx/apps/tests/main-set/014-show/163-show-file-in-files.json
{
    "args": "show $FILES:src/main.cc",
    "patches": {"build  [0-9a-f]{40} (.*)": "build  $BUILD_HASH \\1"},
    "expected": [
        0,
        [
            "file src/main.cc",
            "blob d07753a5e8b4288620503b87170e8245281b2342",
            "functions a31bc21c9db0c9d4d08c20b38e4fc9b21eb5db8b",
            "lines d3b9fe2ed816f528c23b083dd4aee6d74e8beb62",
            "stats 17 9 6, 2 1, 0 0",
            "",
            "+-----------+---------+----------+---------+---------+---------+----------+---------+------------+",
            "| Name      | % Funcs | Relevant | Missing | % Lines | Visited | Relevant | Missing | Line count |",
            "+-----------+---------+----------+---------+---------+---------+----------+---------+------------+",
            "|   main.cc |   50.00 |        2 |       1 |   66.67 |       6 |        9 |       3 |         17 |",
            "+-----------+---------+----------+---------+---------+---------+----------+---------+------------+",
            "",
            "      500x | foo()",
            "  1 |   0x | -void foo() {",
            "  2 |   0x | -    std::cout << \"Hello, \" << name() << \"!\";",
            "  3 |      |  }",
            "  4 |      |  ",
            "        0x | bar()",
            "  5 |  15x | +void bar() {",
            "  6 |      |      foo();",
            "  7 |  10x | +    foo();",
            "  8 |   8x | +    foo();",
            "  9 |   6x | +    foo();",
            " 10 |   4x | +    foo();",
            " 11 |   2x | +    foo();",
            " 12 |   0x | -    foo();",
            " 13 |      |      foo();",
            " 14 |      |      foo();",
            " 15 |      |      foo();",
            "\n"
        ],
        ""
    ],
    "prepare": [
        "unpack $DATA/repo.git.tar $TMP",
        "cd '$TMP'",
        "git clone repo.git",
        "cd '$TMP/repo'",
        "git config --local user.name 'Johnny Appleseed'",
        "git config --local user.email 'johnny@appleseed.com'",
        "cov init",
        "cov report $DATA/build-coverage-show-functions-1.json -f create-report",
        "cov report $DATA/build-coverage-show-functions-2.json -f create-report",
        "store FILES cov log -n1 --format '%HF%n'"
    ]
}

=== mbits-libs/git2-cxx/apps/tests/main-set/015-filters-A/04-strip-excludes-compilerA-OS.json
{
    "$schema": "../../../../tools/json_tests/schema.json",
    "args": "report -f strip-excludes '$DATA/extensions/report-strip.json' -- --os OS --compiler compilerA",
    "post": [
        "show HEAD:main.cc"
    ],
    "patches": {
        "\u001b\\[31m\\[main [0-9a-fA-F]+\\]\u001b\\[m (.*)": "\u001b[31m[main $REPORT]\u001b[m \\1",
        " \u001b\\[2;37mcontains [0-9a-fA-F]+:\u001b\\[m (.+)": " \u001b[2;37mcontains $BUILD:\u001b[m \\1"
    },
    "expected": [
        0,
        [
            "\u001b[31m[main $REPORT]\u001b[m Commit \"extensions\"",
            " one file, \u001b[31m 29%\u001b[m (2/7, -5), Fn\u001b[31m 25%\u001b[m (1/4)",
            " \u001b[2;37mbased on\u001b[m \u001b[2;33m98d4978ec@main\u001b[m",
            " parent 45c01b5bd",
            " \u001b[2;37mcontains $BUILD:\u001b[m \u001b[31m 29%\u001b[m",
            "",
            "file main.cc",
            "blob 8413b254a0751500a3f50ecb1dd93ae4fbf12658",
            "functions 14f0e1233783a10d5073ddcd060500201cf35c29",
            "lines 901e3f666456f35c146cbd93cb9b95b2ad1fa5c0",
            "stats 40 7 2, 4 1, 0 0",
            "",
            "+-----------+--------------+---------+--------------+---------+----------+---------+------------+",
            "| Name      |   % Funcs    | Missing |   % Lines    | Visited | Relevant | Missing | Line count |",
            "+-----------+--------------+---------+--------------+---------+----------+---------+------------+",
            "|   main.cc | 25.00 +25.00 |    3 +3 | 28.57 +28.57 |    2 +2 |     7 +7 |    5 +5 |     40 +40 |",
            "+-----------+--------------+---------+--------------+---------+----------+---------+------------+",
            "",
            "  1 |    |  module;",
            "  2 |    |  import std;",
            "  3 |    |  ",
            "      0x | partial_function_exclusion1",
            "  4 | 0x | -void partial_function_exclusion() /*after*/ {",
            "  5 | 0x | -    line1();",
            "  6 |    |  // GCOV_EXCL_START[OS]",
            "  7 |    |      line2();",
            "  8 |    |      line3();",
            "  9 |    |      line4();",
            " 10 |    |  }",
            " 11 |    |  ",
            " 12 |    |  // GCOV_EXCL_STOP",
            " 13 |    |  ",
            "      0x | sep1",
            " 14 | 4x | +void sep1() {}",
            " 15 |    |  // GCOV_EXCL_START",
            " 16 |    |  ",
            "      0x | partial_function_exclusion2",
            " 17 |    |  void partial_function_exclusion1() /*before*/ {",
            " 18 |    |      line1();",
            " 19 |    |      line2();",
            " 20 |    |  // GCOV_EXCL_STOP",
            " 21 | 0x | -    line3();",
            " 22 | 0x | -    line4();",
            " 23 | 0x | -}",
            " 24 |    |  ",
            "      1x | sep2",
            " 25 | 5x | +void sep2() {}",
            " 26 |    |  ",
            "\n"
        ],
        "strip-excludes: excluded 18 lines, 2 functions\n"
    ],
    "prepare": [
        "unpack $DATA/extensions.tar $TMP",
        "cd '$TMP/extensions'"
    ]
}

=== mbits-libs/git2-cxx/apps/tests/main-set/014-show/152-show-range.json
{
    "args": "show then..",
    "patches": {
        "report [0-9a-f]{40}": "report $REPORT_HASH",
        "commit [0-9a-f]{40}": "commit $COMMIT_HASH",
        "build  [0-9a-f]{40} (.*)": "build  $BUILD_HASH \\1",
        "Added:     .*": "Added:     $NOW"
    },
    "expected": [
        0,
        [
            "report $REPORT_HASH",
            "commit $COMMIT_HASH",
            "build  $BUILD_HASH [ 86%]",
            "GitBranch: main",
            "Coverage:  [ 86%] 6/7 (incomplete)",
            "Author:    Johnny Appleseed <johnny@appleseed.com>",
            "Added:     $NOW",
            "",
            "      reported files",
            "",
            "+---------+-----------------+---------+----------+---------+-------+",
            "| NAME    |    COVERAGE     | COVERED | RELEVANT | MISSING | TOTAL |",
            "+---------+-----------------+---------+----------+---------+-------+",
            "| D lib   |  75.00% -25.00% |    3 -1 |        4 |    1 +1 |     7 |",
            "| D src   | 100.00% +33.33% |    3 +1 |        3 |    0 -1 |     6 |",
            "+---------+-----------------+---------+----------+---------+-------+",
            "| > TOTAL |  85.71%         |    6    |        7 |    1    |    13 |",
            "+---------+-----------------+---------+----------+---------+-------+\n"
        ],
        ""
    ],
    "prepare": [
        "unpack $DATA/repo.git.tar $TMP",
        "cd '$TMP'",
        "git clone repo.git",
        "cd '$TMP/repo'",
        "git config --local user.name 'Johnny Appleseed'",
        "git config --local user.email 'johnny@appleseed.com'",
        "cov init",
        "cov report $DATA/build-coverage-show-modules.json -f create-report",
        "cov tag then",
        "cov report $DATA/build-coverage-show-modules-2.json -f create-report"
    ]
}

=== mbits-libs/git2-cxx/apps/tests/main-set/016-collect/06-collect-observe.json
{
    "$schema": "../../runner-schema.json",
    "linear": true,
    "args": "collect --observe ctest -C Debug .",
    "expected": [
        0,
        "Test project $TMP/observe\n",
        "No tests were found!!!\n"
    ],
    "prepare": [
        "mkdirs '$TMP/observe'",
        "cd '$TMP/observe'",
        "git init",
        "cov init",
        "git commit -m 'initial' --allow-empty",
        "mock hal9000-lcars-GLaDOS-g++-17 g++",
        "mock hal9000-lcars-GLaDOS-gcov-17 gcov",
        "generate '$DATA/covcollect/ini' .covcollect 'COMPILER=$TMP/mocks/g++'"
    ]
}

=== mbits-libs/git2-cxx/apps/tests/main-set/002-init/021-init-no-args-no-cwd.json
{
    "args": "init",
    "patches": {
        "cov init: error: argument -C: .*": "cov init: error: argument -C: ERROR MESSAGE"
    },
    "expected": [
        2,
        "",
        [
            "usage: cov init [-h] [--git-dir <dir>] [--force] [directory]",
            "cov init: error: argument -C: ERROR MESSAGE\n"
        ]
    ],
    "prepare": [
        "safe-rm '$TMP/init-git-dir-no-cwd'",
        "mkdirs '$TMP/init-git-dir-no-cwd/subdir'",
        "cd '$TMP/init-git-dir-no-cwd/subdir'",
        "rm '$TMP/init-git-dir-no-cwd'"
    ]
}
