=== mbits-libs/git2-cxx/tools/json_tests/schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "type": "object",
    "required": ["args", "expected"],
    "properties": {
        "$schema": {"type": "string"},
        "linear": {"type": "boolean"},
        "disabled": {"type": ["string", "boolean"]},
        "lang": {"type": "boolean"},
        "args": {"type": "string"},
        "post": {"type": ["string", "array"], "items": {"type": "string"}},
        "expected": {"type": ["array", "null"]},
        "patches": {
            "type": "object",
            "properties": {
                "^$": {"not": {}},
                "^.+$": {"type": "string"}
            }
        },
        "prepare": {
            "type": ["string", "array"],
            "items": {"type": ["string", "array"], "items": {"type": "string"}}
        },
        "cleanup": {
            "type": ["string", "array"],
            "items": {"type": ["string", "array"], "items": {"type": "string"}}
        }
    },
    "additionalProperties": false,
    "default": {}
}

=== mbits-libs/git2-cxx/apps/tests/main-set/014-show/148-show-no-args-module.json
{
    "args": "show --color=always",
    "patches": {
        "\u001b\\[33mreport [0-9a-f]{40}\u001b\\[m": "\u001b[33mreport $REPORT_HASH\u001b[m",
        "commit [0-9a-f]{40}": "commit $COMMIT_HASH",
        "build  [0-9a-f]{40} (.*)": "build  $BUILD_HASH \\1",
        "Added:     .*": "Added:     $NOW"
    },
    "expected": [
        0,
        [
            "\u001b[33mreport $REPORT_HASH\u001b[m",
            "commit $COMMIT_HASH",
            "build  $BUILD_HASH [ 86%]",
            "GitBranch: main",
            "Coverage:  [ 86%] \u001b[2;37m6/7\u001b[m \u001b[2;33m(incomplete)\u001b[m",
            "Author:    Johnny Appleseed <johnny@appleseed.com>",
            "Added:     $NOW",
            "",
            "      reported files",
            "",
            "+---------+-----------------+---------+----------+---------+-------+",
            "| NAME    |    COVERAGE     | COVERED | RELEVANT | MISSING | TOTAL |",
            "+---------+-----------------+---------+----------+---------+-------+",
            "| M MAIN  | \u001b[1;32m100.00%\u001b[m \u001b[2;32m+33.33%\u001b[m |    3 \u001b[2;32m+1\u001b[m |        3 |    0 \u001b[2;32m-1\u001b[m |     6 |",
            "| D lib   |  \u001b[1;33m75.00%\u001b[m \u001b[2;31m-25.00%\u001b[m |    3 \u001b[2;31m-1\u001b[m |        4 |    1 \u001b[2;31m+1\u001b[m |     7 |",
            "+---------+-----------------+---------+----------+---------+-------+",
            "| > TOTAL |  \u001b[1;33m85.71%\u001b[m         |    6    |        7 |    1    |    13 |",
            "+---------+-----------------+---------+----------+---------+-------+\n"
        ],
        ""
    ],
    "prepare": [
        "unpack $DATA/repo.git.tar $TMP",
        "cd '$TMP'",
        "git clone repo.git",
        "cd '$TMP/repo'",
        "git config --local user.name 'Johnny Appleseed'",
        "git config --local user.email 'johnny@appleseed.com'",
        "cov init",
        "cov module --add MAIN src",
        "cov report $DATA/build-coverage-show-modules.json -f create-report",
        "cov report $DATA/build-coverage-show-modules-2.json -f create-report"
    ]
}

=== mbits-libs/git2-cxx/apps/tests/main-set/012-checkout/132-checkout-branch.json
{
    "args": "checkout -b branch-name",
    "post": [
        "branch --show-current",
        "log --oneline -n1"
    ],
    "expected": [
        0,
        [
            "branch-name",
            "",
            "1232e2f9e    0%  Commit D 0398a2156@main\n"
        ],
        ""
    ],
    "prepare": [
        "unpack $DATA/revparse.tar $TMP",
        "cd $TMP/revparse",
        "cov log --oneline"
    ]
}

=== mbits-libs/git2-cxx/apps/tests/main-set/014-show/158-show-functions.json
{
    "args": "show HEAD:src/main.cc --color always",
    "patches": {
        "report [0-9a-f]{40}": "report $REPORT_HASH",
        "commit [0-9a-f]{40}": "commit $COMMIT_HASH",
        "build  [0-9a-f]{40} (.*)": "build  $BUILD_HASH \\1",
        "Added:     .*": "Added:     $NOW"
    },
    "expected": [
        0,
        [
            "\u001b[33mfile src/main.cc\u001b[m",
            "",
            "+-----------+--------------+---------+---------+---------+----------+---------+------------+",
            "| Name      |   % Funcs    | Missing | % Lines | Visited | Relevant | Missing | Line count |",
            "+-----------+--------------+---------+---------+---------+----------+---------+------------+",
            "|   main.cc | \u001b[1;31m50.00\u001b[m \u001b[2;31m-50.00\u001b[m |    1 \u001b[2;31m+1\u001b[m |   \u001b[1;31m66.67\u001b[m |       6 |        9 |       3 |         17 |",
            "+-----------+--------------+---------+---------+---------+----------+---------+------------+",
            "",
            "\u001b[2;49;39m      500x |\u001b[m \u001b[2;49;32mfoo()\u001b[m",
            "  1 |   0x | \u001b[0;49;31m-\u001b[1;31mvoid\u001b[0;49;31m foo() {\u001b[m",
            "  2 |   0x | \u001b[0;49;31m-    std::cout << \u001b[0;49;91m\"\u001b[2;49;91mHello, \u001b[0;49;91m\"\u001b[0;49;31m << name() << \u001b[0;49;91m\"\u001b[2;49;91m!\u001b[0;49;91m\"\u001b[0;49;31m;\u001b[m",
            "  3 |      |  }",
            "  4 |      |  ",
            "\u001b[2;49;39m        0x |\u001b[m \u001b[2;49;31mbar()\u001b[m",
            "  5 |  15x | \u001b[0;49;32m+\u001b[1;32mvoid\u001b[0;49;32m bar() {\u001b[m",
            "  6 |      |      foo();",
            "  7 |  10x | \u001b[0;49;32m+    foo();\u001b[m",
            "  8 |   8x | \u001b[0;49;32m+    foo();\u001b[m",
            "  9 |   6x | \u001b[0;49;32m+    foo();\u001b[m",
            " 10 |   4x | \u001b[0;49;32m+    foo();\u001b[m",
            " 11 |   2x | \u001b[0;49;32m+    foo();\u001b[m",
            " 12 |   0x | \u001b[0;49;31m-    foo();\u001b[m",
            " 13 |      |      foo();",
            " 14 |      |      foo();",
            " 15 |      |      foo();",
            "\n"
        ],
        ""
    ],
    "prepare": [
        "unpack $DATA/repo.git.tar $TMP",
        "cd '$TMP'",
        "git clone repo.git",
        "cd '$TMP/repo'",
        "git config --local user.name 'Johnny Appleseed'",
        "git config --local user.email 'johnny@appleseed.com'",
        "cov init",
        "cov report $DATA/build-coverage-show-functions-1.json -f create-report",
        "cov report $DATA/build-coverage-show-functions-2.json -f create-report"
    ]
}

=== mbits-libs/git2-cxx/apps/tests/main-set/012-checkout/133-checkout-orphan.json
{
    "args": "checkout --orphan branch-name",
    "post": [
        "branch --show-current",
        "log --oneline -n1"
    ],
    "expected": [
        2,
        "branch-name\n",
        "cov log: error: HEAD refers to branch with no reports\n"
    ],
    "prepare": [
        "unpack $DATA/revparse.tar $TMP",
        "cd $TMP/revparse"
    ]
}

=== mbits-libs/git2-cxx/apps/tests/main-set/014-show/154-show-HEAD..HEAD.json
{
    "$schema": "../../../../build/downloads/runner-schema.json",
    "args": "show same..sies",
    "patches": {
        "report [0-9a-f]{40}": "report $REPORT_HASH",
        "commit [0-9a-f]{40}": "commit $COMMIT_HASH",
        "build  [0-9a-f]{40} (.*)": "build  $BUILD_HASH \\1"
    },
    "expected": [
        0,
        [
            "report $REPORT_HASH",
            "commit $COMMIT_HASH",
            "build  $BUILD_HASH [ 86%]",
            "GitBranch: main",
            "Coverage:  [ 86%] 6/7 (incomplete)",
            "Author:    Johnny Appleseed <johnny@appleseed.com>",
            "Added:     $DATE",
            "",
            "      reported files",
            "",
            "+---------+---------+---------+----------+---------+------------+",
            "| Name    | % Lines | Visited | Relevant | Missing | Line count |",
            "+---------+---------+---------+----------+---------+------------+",
            "| D lib   |  100.00 |       4 |        4 |         |          7 |",
            "| D src   |   66.67 |       2 |        3 |       1 |          6 |",
            "+---------+---------+---------+----------+---------+------------+",
            "| > TOTAL |   85.71 |       6 |        7 |       1 |         13 |",
            "+---------+---------+---------+----------+---------+------------+\n"
        ],
        ""
    ],
    "prepare": [
        "unpack $DATA/repo.git.tar $TMP",
        "cd '$TMP'",
        "git clone repo.git",
        "cd '$TMP/repo'",
        "git config --local user.name 'Johnny Appleseed'",
        "git config --local user.email 'johnny@appleseed.com'",
        "cov init",
        "cov report $DATA/build-coverage-show-modules.json -f create-report",
        "cov tag same",
        "cov tag sies"
    ]
}

=== mbits-libs/git2-cxx/apps/tests/main-set/016-collect--/03-collect-no-HEAD.json
{
    "disabled": true,
    "args": "collect",
    "expected": [
        1,
        "",
        "[git] called on unborn branch\n"
    ],
    "prepare": [
        "mkdirs '$TMP/unborn'",
        "cd '$TMP/unborn'",
        "git init",
        "cov init",
        "mkdirs .git/refs/heads",
        "touch .git/refs/heads/main 'ref: refs/heads/main\n'"
    ]
}

=== mbits-libs/git2-cxx/apps/tests/main-set/016-report-C/05-strip-excludes-verbose-4-linux.json
{
    "disabled": "win32",
    "args": "report $DATA/strip-excludes/coverage-1.json -f strip-excludes -o- -- -vv --os l-cars --compiler gcc",
    "expected": [
        0,
        "{\"$schema\":\"https://raw.githubusercontent.com/mzdun/cov/v0.22.0/apps/report-schema.json\",\"git\":{\"branch\":\"main\",\"head\":\"f8632047e4ea88f5e30bf57570694e5b145c5c0d\"},\"files\":[{\"name\":\"file.cc\",\"digest\":\"sha1:c2d41d07c18b314be45063cd145ca2f9019fb893\",\"line_coverage\":{\"3\":0}}]}",
        [
            "verbose: ON",
            "markers: l-cars and gcc.",
            "sources: $TMP/repo",
            "\u001b[1;37m$TMP/repo/file.cc:12:5:\u001b[m \u001b[1;35mwarning:\u001b[m found GCOV_EXCL_END; did you mean GCOV_EXCL_STOP?",
            "\u001b[1;37m$TMP/repo/file.cc:8:5:\u001b[m \u001b[1;35mwarning:\u001b[m GCOV_EXCL_START not matched with GCOV_EXCL_STOP",
            "-- file.cc:4",
            "     0 | \u001b[2;49;30m}  // GCOV_EXCL_LINE\u001b[m",
            "-- file.cc:17",
            "       | \u001b[2;49;30m\tfoo();  // GCOV_EXCL_LINE\u001b[m",
            "strip-excludes: excluded one line.\n"
        ]
    ],
    "prepare": [
        "unpack $DATA/repo.git.tar $TMP",
        "cd '$TMP'",
        "git clone repo.git",
        "cd repo",
        "cov init",
        "cp '$DATA/strip-excludes/file-2' 'file.cc'"
    ]
}

=== mbits-libs/git2-cxx/apps/tests/main-set/014-show/160-show-functions-log.json
{
    "args": "show --color always HEAD:src",
    "patches": {
        "\u001b\\[33mreport [0-9a-f]{40}\u001b\\[m": "\u001b[33mreport $REPORT_HASH\u001b[m",
        "commit [0-9a-f]{40}": "commit $COMMIT_HASH",
        "build  [0-9a-f]{40} (.*)": "build  $BUILD_HASH \\1"
    },
    "expected": [
        0,
        [
            "\u001b[33mdirectory src/\u001b[m",
            "",
            "+----------------+---------+---------+---------+---------+----------+---------+------------+",
            "| Name           | % Funcs | Missing | % Lines | Visited | Relevant | Missing | Line count |",
            "+----------------+---------+---------+---------+---------+----------+---------+------------+",
            "|   greetings.cc |    \u001b[1;31m0.00\u001b[m |         |  \u001b[1;32m100.00\u001b[m |       4 |        4 |         |          6 |",
            "|   main.cc      |   \u001b[1;31m50.00\u001b[m |       1 |   \u001b[1;31m66.67\u001b[m |       6 |        9 |       3 |         17 |",
            "+----------------+---------+---------+---------+---------+----------+---------+------------+",
            "| > TOTAL        |   \u001b[1;31m50.00\u001b[m |       1 |   \u001b[1;33m76.92\u001b[m |      10 |       13 |       3 |         23 |",
            "+----------------+---------+---------+---------+---------+----------+---------+------------+\n"
        ],
        ""
    ],
    "prepare": [
        "unpack $DATA/repo.git.tar $TMP",
        "cd '$TMP'",
        "git clone repo.git",
        "cd '$TMP/repo'",
        "git config --local user.name 'Johnny Appleseed'",
        "git config --local user.email 'johnny@appleseed.com'",
        "cov init",
        "cov report $DATA/build-coverage-show-functions-3.json -f create-report"
    ]
}
